version: "3"
services:
    reverseproxy:
        build:
            context: .
        image: voffoma/reverseproxy 
    backend-user:
        build:
            context: ../../udacity-c2-restapi-user
        image: voffoma/udacity-restapi-user
    backend-feed:
        build:
            context: ../../udacity-c2-restapi-feed 
        image: voffoma/udacity-restapi-feed
    frontend:
        build:
            context: ../../udacity-c2-frontend 
        image: voffoma/udacity-frontend
